name: Ansible deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout kubesoray repo
      with:
        repository: https://github.com/kubernetes-sigs/kubespray.git
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      with:
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      run: |
        python -m pip install --upgrade pip
        cd kubespray/ 
        pip install -r requirements.txt
        ansible-playbook mitogen.yml
        cp -rfp inventory/sample inventory/labor
