github-action
name: Ansible deploy

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone git@github.com:kubernetes-sigs/kubespray.git
        cd kubespray/ 
        pip install -r requirements.txt
        ansible-playbook mitogen.yml
        cp -rfp inventory/sample inventory/labor