name: Ansible deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kubesoray repo
      uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/kubespray
        ref: release-2.13 
        path: $GITHUB_WORKSPACE/kubespray
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        ls -ltra
        #python -m pip install --upgrade pip
        #cd $GITHUB_WORKSPACE/kubespray 
        #pip install -r requirements.txt
        #ansible-playbook mitogen.yml
        #cp -rfp inventory/sample inventory/labor
